services:
  postgres:
    image: postgres:16-alpine
    container_name: biblioteca-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - biblioteca-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biblioteca"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: biblioteca-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - biblioteca-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  libros:
    build: ./apps/libros
    container_name: biblioteca-libros
    restart: unless-stopped
    environment:
      TCP_PORT: 4001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: biblioteca
      DB_PASS: biblioteca
      DB_NAME: biblioteca_libros
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - biblioteca-net

  prestamos:
    build: ./apps/prestamos
    container_name: biblioteca-prestamos
    restart: unless-stopped
    environment:
      TCP_PORT: 4002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: biblioteca
      DB_PASS: biblioteca
      DB_NAME: biblioteca_prestamos
      LIBROS_TCP_HOST: libros
      LIBROS_TCP_PORT: 4001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      libros:
        condition: service_started
    networks:
      - biblioteca-net

  notificaciones:
    build: ./apps/notificaciones
    container_name: biblioteca-notificaciones
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: biblioteca
      DB_PASS: biblioteca
      DB_NAME: biblioteca_notificaciones
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - biblioteca-net

  gateway:
    build: ./apps/gateway
    container_name: biblioteca-gateway
    restart: unless-stopped
    environment:
      PORT: 3000
      LIBROS_TCP_HOST: libros
      LIBROS_TCP_PORT: 4001
      PRESTAMOS_TCP_HOST: prestamos
      PRESTAMOS_TCP_PORT: 4002
    ports:
      - "3000:3000"
    depends_on:
      - libros
      - prestamos
    networks:
      - biblioteca-net

volumes:
  pg_data:

networks:
  biblioteca-net:
    driver: bridge
